version: "3.9"
services:
  frontend:
    build: .
    container_name: articly_frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8061
    restart: unless-stopped