"""empty message

Revision ID: 934ed774080a
Revises: 3a5818667da8
Create Date: 2024-12-12 20:41:56.026002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '934ed774080a'
down_revision: Union[str, None] = '3a5818667da8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.add_column('users', sa.Column('photo', sa.String(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(), nullable=True))
    op.add_column('users', sa.Column('work_time', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('languages', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('social', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'logo')
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('logo', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'social')
    op.drop_column('users', 'languages')
    op.drop_column('users', 'status')
    op.drop_column('users', 'work_time')
    op.drop_column('users', 'location')
    op.drop_column('users', 'photo')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
