"""empty message

Revision ID: 95bec25cec55
Revises: f589782a8f0b
Create Date: 2024-09-30 00:21:16.285741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95bec25cec55'
down_revision: Union[str, None] = 'f589782a8f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('logo', sa.String(), nullable=False))
    op.add_column('users', sa.Column('last_login_date', sa.ARRAY(sa.DateTime()), nullable=False))
    op.add_column('users', sa.Column('tasks', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('notes', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('users', 'notes')
    op.drop_column('users', 'tasks')
    op.drop_column('users', 'last_login_date')
    op.drop_column('users', 'logo')
    # ### end Alembic commands ###
